# Generated by Django 2.1 on 2018-08-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uername', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('data_last', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
