# Generated by Django 2.1 on 2018-08-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180804_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uername',
            new_name='username',
        ),
    ]
