# Generated by Django 2.1 on 2018-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180804_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_last',
            new_name='last_login',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
