# Generated by Django 2.1 on 2018-08-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_account_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_authenticated',
        ),
    ]
