# Generated by Django 2.1 on 2018-08-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_account_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dislikeNum',
            new_name='dislike_num',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='likeNum',
            new_name='like_num',
        ),
    ]
