# Generated by Django 2.1 on 2018-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180805_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_like', models.IntegerField()),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('like_type', models.BooleanField(default=True)),
            ],
        ),
    ]
