# Generated by Django 2.1 on 2018-08-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_like_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='person_like',
            new_name='person_id',
        ),
    ]
