# Generated by Django 2.1 on 2018-08-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20180805_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
